- hosts: "{{ srv }}"
  become: true
  roles:
    - { role: docker, tags: ["docker"]} 
    - { role: generate_certificates, tags: ["generate_certificates"]}
    - { role: nginx-proxy, tags: ["nginx-proxy"]}
    