#docker_vm group vars
network_name: nginx-net
network_subnet: 172.24.4.0/24

nginx_image: nginx:1.23.3
nginx_hostname: nginx_proxy
nginx_memory: 512m
nginx_conf_dir: /usr/share/nginx/

vaultwarden_hostname: 192.168.4.25:8888
vaultwarden_dnsname: "{{ domain_name }}"
certbot_dnsnames: 
  - "{{ domain_name }}"

cerbot_image: certbot/certbot:v1.32.2
cerbot_hostname: cerbot
cerbot_memory: 128m
cerbot_conf_dir: /usr/share/cerbot/